# Generated by Django 5.2.5 on 2025-08-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('picture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
    ]
